#!/usr/bin/env python3
"""Generate src-tauri/src/oui_data.rs from Wireshark's `manuf` database.

Usage:
    curl -sL https://www.wireshark.org/download/automated/data/manuf -o /tmp/manuf
    python3 scripts/gen_oui_data.py /tmp/manuf > src-tauri/src/oui_data.rs

Output is a sorted static array of (prefix, mask_bits, short_vendor) tuples.
24-bit (MA-L) entries are exact-3-octet prefixes; 28/36-bit (MA-M/MA-S)
entries carry their mask width and are matched by masking in oui.rs lookup.
"""

import sys

src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/manuf"

entries = []  # (prefix_int, bits, name)
with open(src, "r", encoding="utf-8", errors="replace") as f:
    for line in f:
        if line.startswith("#") or not line.strip():
            continue
        parts = line.rstrip("\n").split("\t")
        parts = [p.strip() for p in parts if p.strip()]
        if len(parts) < 2:
            continue
        block, short = parts[0], parts[1]
        long_name = parts[2] if len(parts) > 2 else None
        # Choose display name: prefer readable short, fall back to long
        name = short if 2 <= len(short) <= 24 else (long_name or short)
        name = name.replace("\\", "").replace('"', "'").strip()
        if not name:
            continue
        if "/" in block:
            hexpart, bits_s = block.split("/")
            bits = int(bits_s)
        else:
            hexpart, bits = block, 24
        hexpart = hexpart.replace(":", "").replace("-", "")
        try:
            prefix = int(hexpart, 16)
        except ValueError:
            continue
        if bits not in (24, 28, 36):
            continue
        entries.append((prefix, bits, name))

# De-dup and sort by (bits, prefix) — lookup scans 24-bit exacts first.
seen = set()
uniq = []
for e in entries:
    if e not in seen:
        seen.add(e)
        uniq.append(e)
uniq.sort(key=lambda e: (e[1], e[0]))

out = []
out.append("//! GENERATED by scripts/gen_oui_data.py from Wireshark `manuf`")
out.append("//! (IEEE OUI allocations). Do not edit by hand — regenerate instead.")
out.append("")
out.append("/// (prefix, mask_bits, vendor) — mask_bits ∈ {24, 28, 36}.")
out.append("pub static OUI_ENTRIES: &[(u64, u8, &str)] = &[")
for prefix, bits, name in uniq:
    out.append(f'    (0x{prefix:X}, {bits}, "{name}"),')
out.append("];")
out.append("")

sys.stdout.write("\n".join(out))
sys.stderr.write(f"generated {len(uniq)} entries\n")
