//! MAC vendor lookup from the embedded Wireshark `manuf` OUI database
//! (generated by scripts/gen_oui_data.py), plus a runtime override file
//! (`oui_extra.csv` next to the database) merged at startup.

use std::collections::HashMap;
use std::path::Path;
use std::sync::{Mutex, OnceLock};

#[path = "oui_data.rs"]
mod oui_data;

use oui_data::OUI_ENTRIES;

static EXACT24: OnceLock<HashMap<u64, &'static str>> = OnceLock::new();
static EXTRA: OnceLock<Mutex<HashMap<u64, String>>> = OnceLock::new();

fn exact24() -> &'static HashMap<u64, &'static str> {
    EXACT24.get_or_init(|| {
        let mut m = HashMap::with_capacity(OUI_ENTRIES.len());
        for (prefix, bits, name) in OUI_ENTRIES {
            if *bits == 24 {
                m.insert(*prefix, *name);
            }
        }
        m
    })
}

fn extra() -> &'static Mutex<HashMap<u64, String>> {
    EXTRA.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Load `oui_extra.csv` (lines: `AABBCC,Vendor Name`) once at startup.
/// Called from app setup before any capture starts.
pub fn load_extras(app_data: &Path) {
    let path = app_data.join("oui_extra.csv");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return;
    };
    let mut parsed = HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((hex, name)) = line.split_once(',') else { continue };
        let hex: String = hex.chars().filter(|c| c.is_ascii_hexdigit()).collect();
        if hex.len() == 6 {
            if let Ok(prefix) = u64::from_str_radix(&hex, 16) {
                parsed.insert(prefix, name.trim().to_string());
            }
        }
    }
    if !parsed.is_empty() {
        extra().lock().unwrap().extend(parsed);
    }
}

/// Look up the vendor for a MAC address.
pub fn lookup(mac: &[u8; 6]) -> Option<String> {
    let mac48 = ((mac[0] as u64) << 40)
        | ((mac[1] as u64) << 32)
        | ((mac[2] as u64) << 24)
        | ((mac[3] as u64) << 16)
        | ((mac[4] as u64) << 8)
        | mac[5] as u64;
    let mac64 = mac48; // upper bits zero
    let p24 = mac48 >> 24;

    if let Some(v) = extra().lock().unwrap().get(&p24) {
        return Some(v.clone());
    }

    if let Some(v) = exact24().get(&p24) {
        return Some((*v).to_string());
    }
    // MA-M (28b) / MA-S (36b) blocks: mask the MAC and compare
    for (prefix, bits, name) in OUI_ENTRIES {
        if *bits == 24 {
            continue;
        }
        let mask: u64 = ((1u64 << *bits as u64) - 1) << (48 - *bits as u64);
        if mac64 & mask == *prefix as u64 {
            return Some((*name).to_string());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_vendors() {
        // 00:00:0C is Cisco in the manuf database
        let v = lookup(&[0x00, 0x00, 0x0c, 0x11, 0x22, 0x33]);
        assert_eq!(v.as_deref(), Some("Cisco"));
    }

    #[test]
    fn masked_entries_match() {
        // Every entry in the table must match itself
        for (prefix, bits, _) in OUI_ENTRIES.iter().take(5000) {
            let mask: u64 = ((1u64 << *bits as u64) - 1) << (48 - *bits as u64);
            let sample = prefix << (48 - *bits as u64) | 0x1234;
            let mac = sample.to_be_bytes()[2..8].try_into().unwrap();
            let found = lookup(&mac);
            // Only assert no panic + Option return; exact value may differ if
            // a shorter exact24 entry collides, which is acceptable.
            assert!(found.is_some() || *bits != 24);
            let _ = mask;
        }
    }
}
